export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_GLUTEN_FREE_PRODUCTS = "GET_GLUTEN_FREE_PRODUCTS";
export const GET_VEGETARIAN_PRODUCTS = "GET_VEGETARIAN_PRODUCTS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";